language: r

sudo: required
dist: trusty


notifications:
  email:
    recipients:
      - zheng.bangyou@gmail.com
    on_success: always
    on_failure: always

install:
   - Rscript -e "if (!require('ggplot2')) install.packages('ggplot2')"
   - Rscript -e "if (!require('devtools')) install.packages('devtools')"
   - Rscript -e "if (!require('xml2')) install.packages('xml2')"
   - Rscript -e "if (!require('dplyr')) install.packages('dplyr')"
   - Rscript -e "if (!require('tidyr')) install.packages('tidyr')"
   - Rscript -e "if (!require('readr')) install.packages('readr')"
   - Rscript -e "if (!require('pander')) install.packages('pander')"
   - Rscript -e "if (!require('rmarkdown')) devtools::install_github('rstudio/rmarkdown')"
   
before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

cache:
  - packages: yes
  - directories:
    - $HOME/APSIM-Wheat-Sens/site-output/cache
