---
params:
    para: !r list(text = "PotentialExtinctionCoeff", para = list(list(name = "[Leaf].ExtinctionCoeff.PotentialExtinctionCoeff.XYPairs.X", level = c("0, 0.5", "0.0, 0.5", "0.0, 0.5")), list(name = "[Leaf].ExtinctionCoeff.PotentialExtinctionCoeff.XYPairs.Y", level = c("0.3, 0.3", "0.5, 0.5", "0.7, 0.7"))), href = "PotentialExtinctionCoeff.html")

---

---
title: `r params$para$text`
---

# `r params$para$text`


```{r setup, message=FALSE, echo=FALSE, warning=FALSE}
library(knitr)
library(pander)
opts_chunk$set(
    cache = FALSE, echo = FALSE, 
    out.width = '100%', fig.asp = 1,
    warning = FALSE, fig.align = 'center',
    message = FALSE) 
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(xml2)
source('_utility.R')
```

```{r read_data}

para <- params$para
input <- paste0('_simulation/', para$text, '.db.Report.csv')
df <- read.csv(input)

x_var <- c(
    'Wheat.Phenology.Stage',
    'Wheat.Phenology.AccumulateThermalTime')
x_lab <- 'Accumulated thermal time or stage'

```

## Configuration

The sensitivity analysis is conducted for parameter(s).

```{r para_name, results='asis'}
lapply(para$para, function(x) x$name) %>% 
    pandoc.list(style = 'ordered')
```


The table below shows the values of dummy cultivars. The column name(s) only contain the last section of parameter names.


```{r configuration}

levels <- unlist(lapply(para$para, function(x) length(x$level)))
if (mean(levels) != min(levels)) {
    stop('Levels do not have the same length')
}
level_num <- levels[1]

value <- as.data.frame(lapply(para$para, function(x) {
    y <- list()
    name <- gsub('.*\\.(.*)', '\\1', x$name)
    y[[name]] <- x$level
    y
}))

data.frame(Cultivar = paste0('Dummy', seq(length = level_num))) %>% 
    cbind(value) %>% 
        kable(align = 'r')

```


## Phenology 


```{r leaf-tt-stage, fig.asp=0.75, fig.cap='The growthing stage as a function of accumulated thermal  time '}

plot_report(
    df, 
    x_var = 'Wheat.Phenology.AccumulateThermalTime', 
    y_cols = 'Wheat.Phenology.Stage', 
    x_lab = 'Accumulated thermal time (oCd)', 
    y_lab = 'Stage') +
    scale_y_continuous(breaks = seq(1, 10))

```


## Structure

## Leaf development

### Leaf number



```{r leaf-cohort-number, fig.asp = 1.4, fig.cap='Initialized, appeared and expanding cohort number'}
y_cols <- c(
            'Wheat.Leaf.ExpandingCohortNo',
            'Wheat.Leaf.InitialisedCohortNo',
            'Wheat.Leaf.AppearedCohortNo',
            'Wheat.Leaf.SenescingCohortNo',
            'Wheat.Leaf.DeadCohortNo')

plot_report(df, x_var, y_cols, x_lab = x_lab, 
            y_lab = 'Cohort number')


```




```{r leaf-number, fig.asp = 1.3, fig.cap='Appeared number of green, senesced and total leaves'}
y_cols <- c(
    'Wheat.Leaf.PlantAppearedLeafNo',
    'Wheat.Leaf.PlantAppearedGreenLeafNo',
    'Wheat.Leaf.PlantsenescedLeafNo')

plot_report(df, x_var, y_cols, x_lab = x_lab, 
            y_lab = 'Leaf number')

```

### Leaf area index

```{r leaf-lai, fig.cap='Leaf area index'}
y_cols <- c(
    'Wheat.Leaf.LAI', 
'Wheat.Leaf.LAIDead',
'Wheat.Leaf.LAITotal')
plot_report(df, x_var, y_cols, x_lab = x_lab, y_lab = 'Leaf area index')

```

### Coverage

```{r leaf-cover, fig.cap='Coverage'}
y_cols <- c(
    'Wheat.Leaf.CoverGreen',
    'Wheat.Leaf.CoverDead',
    'Wheat.Leaf.CoverTotal')
plot_report(df, x_var, y_cols, x_lab = x_lab, y_lab = 'Coverage')

```







